[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://shl-recommendation-api.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200